name: Processor features
on:
  push:
    branches:
      - master
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go latest
        uses: actions/setup-go@v4

      - name: Vet
        run: go vet ./...
      - name: Build
        run: go install ./...
      - run: | # Tests
          go test -v ./...
